### PR TITLE
Update DownloadingForm.cs

### PR DESCRIPTION
**Pull request by StrangersThings**

### CODE REVIEW

**Comment by Dax-Eleven** [comment]
Ahaha, why do you need so much porn? 🙂

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by StrangersThings** [comment]
hahaha i know, but i have a question for your new update, i search on
rule34 web (league_of_legends have more 70000 media) but when download on
your app just have more than 16000 media can download, i don't understand,
with your code i'm reading. Thanks

Vào Th 4, 22 thg 2, 2023 vào lúc 11:22 Eleven ***@***.***>
đã viết:

**Comment by Dax-Eleven** [comment]
In version 1.0.3 I increased the limit to unsigned 16-bit integer (from 0 to 65535)
If you're wondering why I set a limit at all, then it's simple - I don't want someone to take and make a dump (copy) of the site. It can also be used as a DDoS attack. I have nothing to do with the creators of the site, I just treat them with respect.

**Comment by StrangersThings** [comment]
can i chat with you without using email?


Vào CN, 5 thg 3, 2023 vào lúc 09:55 Eleven ***@***.***> đã
viết:

**Comment by DaxEleven** [comment]
Yes, sign in github.com and open this link
https://github.com/DaxEleven/Rule34.xxx-Downloader/pull/7
:)

**Comment by DaxEleven** [comment]
If you have something to discuss, use the Discussions tab

image

**Pull request closed without merging**
